### ISSUE TITLE
Failed to install 'cordova-plugin-crosswalk-webview-v3': Error: Cannot find module 'q'

### ISSUE THREAD

**Issue by AlwaysLoveme** [ardabeyazoglu/cordova-plugin-crosswalk-webview-v3#1]
i am using width cordova@9.0.0, but get an error "Cannot find module 'q'"

**Comment by ardabeyazoglu** [comment]
@AlwaysLoveme 
This must have been resolved already. Can you run `cordova plugin ls` and tell me the exact version of this plugin ?

UPDATE: I think you dont have "q" npm module inside your node_modules directory. Can you delete node_modules folder and rebuild ?

**Comment by davidsharp** [comment]
I'm also having this issue, `cordova-plugin-crosswalk-webview-v3 3.0.0 "Crosswalk WebView Engine"`

I have `q` in my node_modules folder, but can't build or remove this plugin as it can't find `q`

**Comment by ardabeyazoglu** [comment]
@davidsharp last version is 3.0.2. Can you delete everything about this plugin first, then reinstall running `cordova plugin add cordova-plugin-crosswalk-webview-v3@latest`?

**Comment by davidsharp** [comment]
I have, but while my `config.xml` says 3.0.2, my `cordova plugin ls` still says 3.0.0

(worth pointing out, I get the same behaviour if I `cordova plugin add cordova-plugin-crosswalk-webview-v3@3.0.2`)

**Comment by ardabeyazoglu** [comment]
I suggest you to first remove the plugin folder from plugins dir, delete the releavant row from plugins/android.json (and/or fetch.json), delete from package.json and package.lock as well as node_modules dir. Afterwards make a clean install of plugin. In my environment, I dont have this issue with latest cordova.
