### ISSUE TITLE
play store issue

### ISSUE THREAD

**Issue by ghost** [ardabeyazoglu/cordova-plugin-crosswalk-webview-v3#11]
Hello, 
Google Play Store had stopped accepting app with targetSdkVersion 28.

We should atleast use sdk version 29.
But your code is crashing with targetSdkVersion 29

`E/chromium: [ERROR:compositor_impl_android.cc(585)] Failed to init OutputSurface for compositor.`

Please give me a fix

**Comment by ghost** [comment]
can anyone give me a fix

**Comment by ardabeyazoglu** [comment]
There is no problem about target sdk version, a lot of people are building without problems. You probably have some other issue. Try to update cordova and recreate cordova-android platform with latest version.

**Comment by ghost** [comment]
you have mentioned yourself that " this code does not work with android 10"

**Comment by ardabeyazoglu** [comment]
Only crosswalk is not working android 29+
