### ISSUE TITLE
Disable crosswalk for android 10+

### ISSUE THREAD

**Issue by AlphaSystemsPL** [ardabeyazoglu/cordova-plugin-crosswalk-webview-v3#13]
Can you add the ability to disable crosswalk for android 10+ (SDK 29). I don't care about the size of the app and I don't want to split the application into two projects

**Comment by ardabeyazoglu** [comment]
@VVilquack currently it is not supported, but you can maybe do it as described in #9. I recommend to make different projects/builds and drop support for older devices slowly.
