### ISSUE TITLE
Enabling proprietary codecs

### ISSUE THREAD

**Issue by FurtherMarket** [ardabeyazoglu/cordova-plugin-crosswalk-webview-v3#15]
Hello

Videos playback is very poor when adding this plugin to our application. By default codec for
MP3 audio codec
AAC audio codec
H.264 video codec
are not enabled.

https://github.com/crosswalk-project/crosswalk-website/wiki/Enable-MultiMedia-in-Crosswalk

Can we please have a build with these codecs anabled?

**Comment by ardabeyazoglu** [comment]
This is not right place to for this question but anyway Crosswalk chromium is not maintained anymore so nobody would do that development.
