### ISSUE TITLE
Support for Android SDK 29

### ISSUE THREAD

**Issue by mynickbusy** [ardabeyazoglu/cordova-plugin-crosswalk-webview-v3#17]
Hi same question, if Crosswalk is not supported for Android SDK 29 then how then to get armv7 and arm64 build for google play console or how to get arm64 without using Crosswalk

how to create assemblies for google play console without errors if SDK 29 is required

**Comment by mynickbusy** [comment]
Do you suggest uploading the sdk level 26 to google play and upload is successful?

or need to do something like this

**one with crosswalk //  cordova build --release --xwalk64bit**

**one without  //  cordova build android --release**

> Crosswalk does not work for Android 10+ devices. I recommend you split the app in 2 different projects, one with crosswalk and one without. The one without crosswalk must support minimum android 7 (sdk level 26).

**Comment by ardabeyazoglu** [comment]
I recommend you keep two copies of the app, one with crosswalk.  One with crosswalk must have lower version code, and one without crosswalk must have minSdkVersion set to 26. That is what i am doing.

**Comment by mynickbusy** [comment]
android@9.0.0 platform will have the same performance as android@7.1.4 + crosswalk?

**Comment by ardabeyazoglu** [comment]
android 7.1+ has better formance without crosswalk to my experience + much smaller bundle size

**Comment by mynickbusy** [comment]
> I recommend you keep two copies of the app, one with crosswalk. One with crosswalk must have lower version code, and one without crosswalk must have minSdkVersion set to 26. That is what i am doing.

My settings when I try to build apk build for play market
Cordova version is 9.0.0 (cordova-lib@9.0.1)
Android platform version - 9.0.0

**And everything works well**



My settings when I try to build apk build for play market via Crosswalk

Cordova version is 8.1.2 (cordova-lib@8.1.1)
Android platform version - 7.1.4

**when loading error:**
The target API level for your application is 27. The target API level for your application must be at least 29 to provide the required performance and security. Change the target API level for your application to at least 29.

But I can't change here 27 to 29

**Comment by ardabeyazoglu** [comment]
Your target api level must be set 29 as in the warning. You can put this to config.xml.

```
<platform name="android">
        <preference name="android-minSdkVersion" value="20" />
        <preference name="android-targetSdkVersion" value="29" />
</platform>
```
For the one without crosswalk:

```
<platform name="android">
        <preference name="android-minSdkVersion" value="26" />
        <preference name="android-targetSdkVersion" value="30" />
</platform>
```

**Comment by mynickbusy** [comment]
> <preference name="android-targetSdkVersion" value="29" />

I already did this and the application crashes / closes immediately after launch, but thanks anyway for the help, I will think further :))))

**Comment by tdfeslo** [comment]
hi, i have an application with the cordova crosswalk plugin deployed in production environment for about 2 years and it works on my android 10 phone. Is it when upgrading the crosswalk plugin version that it crashes?

**Comment by mynickbusy** [comment]
> hi, i have an application with the cordova crosswalk plugin deployed in production environment for about 2 years and it works on my android 10 phone. Is it when upgrading the crosswalk plugin version that it crashes?

Hi, so far I have decided to abandon crosswalk altogether, but the crashes and crashes were precisely because of the line `<preference name = "android-targetSdkVersion" value = "29" />`

**Comment by mynickbusy** [comment]
And I also understand that cordova works fine starting with android 6 and without crosswalk, then the question is why this plugin is needed to support android 5 and 4?)), In my opinion this is not necessary

**Comment by tdfeslo** [comment]
Thanks for you reply.
I have to upgrade my cordova project and i have set this :
`
        <preference name="android-minSdkVersion" value="19" />
        < preference name="android-targetSdkVersion" value="29" />
`
I would test this after the weekend because indeed I havn't not yet tested on a device with Android 10.

**Comment by mynickbusy** [comment]
try and tell me what the result will be)) since I tried 100.5 million attempts to build the release version and there were always errors during build, these were all possible errors that eventually made me completely uninstall the Crosswalk plugin, and only after that managed to create a version for Google Play, but the application stopped working on android 4 - 5, well, okay :)

**Comment by tdfeslo** [comment]
I just realized that I have to use a cordova plugin for the TouchId which requires at least SDK version 23 (Android 6). So actually I am wondering about the usefulness of still using crosswalk finally ^^

**Comment by tdfeslo** [comment]
Otherwise I just tried and I confirm you were right the application crashed at launch on Android 10.

**Comment by AlphaSystemsPL** [comment]
You must add to your crosswalk version
`<preference name="android-maxSdkVersion" value="28" />`
