### ISSUE TITLE
Need support for both 32 bit and 64 bit arch.

### ISSUE THREAD

**Issue by sreenubkaimal** [ardabeyazoglu/cordova-plugin-crosswalk-webview-v3#2]
Hi,
We updated crosswalk webview to support 64-bit architecture But we need to support 32 bit architecture too.. 
Noticed the installation instruction as below  - 
"If you don't need to support older devices with 32bit architectures, you should only build for 64-bit, sign and upload them to play store. However, if there are still older devices running your app, you must build and sign all 4 of them and upload each to play store."

But play store does not allow uploading of apk meant only for 32 bit. It throws error there. Any idea on how to upload multiple apks ?
Or
Any possibility of building a single apk supporting both 32 bit and 64 bit architecture ?

**Comment by ardabeyazoglu** [comment]
Hi @sreenubkaimal,

As far as i know, you cant support all of them inside one apk. But you can support both platforms like i do. Create 2 apks for 32bit and 2 apks for 64bit, upload all 4 of them. Google will install the appropriate one for each device.
Why would you explicitly need *single* apk for all ?

UPDATE:
Also, you can check my build and sign script for them on this [gist](https://gist.github.com/ardabeyazoglu/ff505d06bd576b966ad7f1c932f7c6ed)

**Comment by sreenubkaimal** [comment]
Hi
Thanks for the response.
I understand that above briefing about my issue is confusing.
There is option to upload only one APK in Google Play Console, and it should support 64 bit Android.
Generally when a native app is built and an APK is uploaded, the app can be downloaded on 64 bit and 32 bit phones, as it is backward compatible.
In this case, it is not happening that way.

To be more precise  -

We have a cordova project which was built usinf Ember Cli framework.,(This was developed by another team whom we do not know). 
Now we are trying to make it compatible for 64 bit Android architecture 
First challenge was that we could not build it using cordova commands.. So we have built the same using Android studio.
When using this version of Crosswalk webview, with the settings --- 
<preference name="xwalk64bit" value ="true" />
generated APK is not getting installed on 32 bit phone.

If we build for multiple variants, we are able to generate apk for 32 bit. But how will these 2 versions be maintained in Play console, as it doesnt allow upload of 32 but APK now ?

**Comment by sreenubkaimal** [comment]
Hi
Thanks for the response.
I understand that above briefing about my issue is confusing.
There is option to upload only one APK in Google Play Console, and it should support 64 bit Android.
Generally when a native app is built and an APK is uploaded, the app can be downloaded on 64 bit and 32 bit phones, as it is backward compatible.
In this case, it is not happening that way.
To be more precise -
We have a cordova project which was built usinf Ember Cli framework.,(This was developed by another team whom we do not know).
Now we are trying to make it compatible for 64 bit Android architecture
First challenge was that we could not build it using cordova commands.. So we have built the same using Android studio.
When using this version of Crosswalk webview, with the settings ---

generated APK is not getting installed on 32 bit phone.
If we build for multiple variants, we are able to generate apk for 32 bit. But how will these 2 versions be maintained in Play console, as it doesnt allow upload of 32 but APK now ?


Regards
Sreenu B Kaimal
Sonata Software Limited
Phone : +91 80 6778 2435
Mobile : +91 9448020230
www.sonata-software.com<http://www.sonata-software.com/>

Please don't print this email unless you really need to. This will preserve trees on our planet

**Comment by ardabeyazoglu** [comment]
@sreenubkaimal Of course it allows uploading 32bit apk. This is what i do. However, It does not allow an app to have *only 32bit apks*. Thats why the best thing to do is, to build both of them and upload all of them. Google will decide which one to install on different devices. Though, i dont know ember cli so i cant help on that.

**Comment by sreenubkaimal** [comment]
Thanks a lot for quick response.

Do you mean to say – after uploading a 64 bit apk, there is an option to upload 32 bit apk too ?
I have not noticed / done that yet ☹

Regards
Sreenu B Kaimal
Sonata Software Limited
Phone : +91 80 6778 2435
Mobile : +91 9448020230
www.sonata-software.com<http://www.sonata-software.com/>

Please don't print this email unless you really need to. This will preserve trees on our planet

**Comment by ardabeyazoglu** [comment]
Yes, you can upload different arch apks one by one before publishing. As long as there are 64bit apks and no version code mismatch, google will accept it.

**Comment by sreenubkaimal** [comment]
Thanks for the response. Will try that

Regards
Sreenu B Kaimal
Sonata Software Limited
Phone : +91 80 6778 2435
Mobile : +91 9448020230
www.sonata-software.com<http://www.sonata-software.com/>

Please don't print this email unless you really need to. This will preserve trees on our planet
