### ISSUE TITLE
'require' vs. 'context.requireCordovaModule' in hooks/update_config.js

### ISSUE THREAD

**Issue by memken** [ardabeyazoglu/cordova-plugin-crosswalk-webview-v3#4]
First of all, thank you very much for the work you've done on this!

This is more of a question/clarification than an issue, but I wasn't sure where else to post.

In hooks/update_config.js you updated the 'context.requireCordovaModule' to 'require' for:

    var fs = require('fs'),
        path = require('path'),
        et = require('elementtree');

But did not make any changes in this regard to ConfigParser or XmlHelpers:

    try {
        // cordova-lib >= 5.3.4 doesn't contain ConfigParser and xml-helpers anymore
        ConfigParser = context.requireCordovaModule("cordova-common").ConfigParser;
        XmlHelpers = context.requireCordovaModule("cordova-common").xmlHelpers;
    } catch (e) {
        ConfigParser = context.requireCordovaModule("cordova-lib/src/configparser/ConfigParser");
        XmlHelpers = context.requireCordovaModule("cordova-lib/src/util/xml-helpers");
    }

Was this intended? Or do these lines need to be updated as well? Thanks for your time and clarification!

**Comment by ardabeyazoglu** [comment]
@memken using requireCordovaModule to import non-cordova modules is deprecated. Latter ones are cordova modules so they must stay as it is.

**Comment by memken** [comment]
Thanks!
