### ISSUE TITLE
libxwalkcore.so for 32-bit builds are missing

### ISSUE THREAD

**Issue by memken** [ardabeyazoglu/cordova-plugin-crosswalk-webview-v3#6]
This is in reference to https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/issues/264

In building 32 bit versions, libxwalkcore.so for 32-bit builds are missing. Was wondering if you have any insight into this as there's been no response on the original repo.

Thank you!

**Comment by memken** [comment]
Bump.

Wanted to check to see if there's any information on this. Thank you!

**Comment by ardabeyazoglu** [comment]
@memken I never encountered problem like that. I have the following options in config.xml.

<plugin name="cordova-plugin-crosswalk-webview-v3" spec="~3.0.3">
        <variable name="XWALK_VERSION" value="23+" />
        <variable name="XWALK_LITEVERSION" value="xwalk_core_library_canary:17+" />
        <variable name="XWALK_COMMANDLINE" value="--disable-pull-to-refresh-effect" />
        <variable name="XWALK_MODE" value="embedded" />
        <variable name="XWALK_MULTIPLEAPK" value="true" />
    </plugin>
