### ISSUE TITLE
Does not use crosswalk for Android N

### ISSUE THREAD

**Issue by renanbandeira** [ardabeyazoglu/cordova-plugin-crosswalk-webview-v3#9]
I was looking for some upgrade on Chromium version and I found this PR on a fork repository: https://github.com/Arva/cordova-plugin-crosswalk-webview/pull/2

it would be great if this repository could have this fix too.

**Comment by ardabeyazoglu** [comment]
@renanbandeira for android 10+ crosswalk is indeed not working, and there is no way to make it work because original crosswalk project is archived. I recommend you drop crosswalk for android 7+ devices, by creating multiple apks.

**Comment by atmanegara** [comment]
> @renanbandeira for android 10+ crosswalk is indeed not working, and there is no way to make it work because original crosswalk project is archived. I recommend you drop crosswalk for android 7+ devices, by creating multiple apks.


are there alternatives like crosswalk?

**Comment by renanbandeira** [comment]
Have you seen the link I posted? That fork uses crosswalk plugin only for Android < 5..one apk that loads crosswalk only if it is necessary. We are currently using it and it works as desired

**Comment by atmanegara** [comment]
> Have you seen the link I posted? That fork uses crosswalk plugin only for Android < 5..one apk that loads crosswalk only if it is necessary. We are currently using it and it works as desired

yaa, thanks sir

**Comment by ardabeyazoglu** [comment]
I can merge if there is pull request of relevent fix. However, using multiple apks still makes more sense to me because crosswalk plugin adds around 20mb to final apk size as well as native architecture code.

**Comment by rahulchaube** [comment]
@renanbandeira  Thanks sir for the advice. Arva#2 this plugin is working for us as well. However, I see one small issue. The font styles have changed after installing this plugin. Did you face this issue as well, if Yes, could you throw some light on how to fix this.

Regards,
Rahul Chaube
